# example netlify.toml
[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"

[[redirects]]
  from = "/install.sh"
  to = "https://raw.githubusercontent.com/neilotoole/sq/master/install.sh"
  status = 301

